### ISSUE TITLE
Fabulous Error

### ISSUE THREAD

**Issue by gorani159** [BalintCsala/VanillaPuddingTart#16]
Minecraft vanilla 1.19
GPU : RTX 3070TI

It doesn't apply even if you apply it according to the instructions
![1112](https://user-images.githubusercontent.com/97017268/207542112-fc166982-83e5-44de-ab29-eaf1ed260cf6.JPG)

Even in Fabulous mode, it's like this
![2022-12-14_17 11 04](https://user-images.githubusercontent.com/97017268/207541707-9dbbea13-3a9e-48c4-96f9-3ad52168f2ee.png)
This is a good shader
If it is used, I want to apply it to the server

**Comment by BalintCsala** [comment]
Please post ".minecraft/logs/latest.log" to here, so that I can take a look at it

If by "I want to apply it to the server" you mean you want to upload it to a server, so that the players on it get it, I'd ask you to not do that, since 
 1.) It's very heavy on the performance
 2.) It needs fabulous mode on
 3.) It's my product and I don't want you to distribute it in any form
 4.) The generated packs are someone else's product and you most likely can't legally redistribute those either

**Comment by gorani159** [comment]
[latest.log](https://github.com/BalintCsala/VanillaPuddingTart/files/10225883/latest.log)

Resource packs that apply to servers can be locked
No one can open and deploy because it is locked with PackSquash.
https://github.com/ComunidadAylas/PackSquash/releases
Let me also specify the source
If BalintCsala cannot apply to the server, we will stop

**Comment by BalintCsala** [comment]
You didn't follow the installation instructions correctly, the pack needs to go through a conversion to make it work with VPT: https://blog.balintcsala.com/posts/vpt-setup/#converting-the-resourcepack

I've seen packs done with packsquash before, e.g. the animation system in origin realms and it has absolutely not stopped redistribution. There are ways around it, if the system in the game can open it, there's nothing stopping people from just yanking that out and creating an unpacker for it.

**Comment by gorani159** [comment]
I won't apply it to the server.
When I saw this resource, I felt the potential of Vanilla's resource pack Shader is so cool
I'm going to sponsor you

**Comment by BalintCsala** [comment]
Thanks for understanding. Was the issue resolved?
